import { WIDGET_PRESENTATION_CONTRACT_VERSION, type WidgetPresentationManifest } from "../../../widgetPresentation/types";

export const simpleWorkspaceWidgetPresentation: WidgetPresentationManifest = Object.freeze({
    contractVersion: WIDGET_PRESENTATION_CONTRACT_VERSION,
    generic: Object.freeze({ id: "simple.workspace.generic" }),
    kinds: Object.freeze({
        list: Object.freeze({ id: "simple.workspace.list" }),
        task: Object.freeze({ id: "simple.workspace.task" }),
        stat: Object.freeze({ id: "simple.workspace.stat" }),
        chart: Object.freeze({ id: "simple.workspace.chart" }),
        calendar: Object.freeze({ id: "simple.workspace.calendar" }),
        note: Object.freeze({ id: "simple.workspace.note" }),
        media: Object.freeze({ id: "simple.workspace.media" }),
        utility: Object.freeze({ id: "simple.workspace.utility" }),
        embed: Object.freeze({ id: "simple.workspace.embed" }),
        complex: Object.freeze({ id: "simple.workspace.complex" }),
        custom: Object.freeze({ id: "simple.workspace.custom" }),
    }),
    widgets: Object.freeze({
        "latest-docs": Object.freeze({ id: "simple.workspace.latest-docs", scope: "full" }),
        favorites: Object.freeze({ id: "simple.workspace.favorites", scope: "full" }),
        "recent-journals": Object.freeze({ id: "simple.workspace.recent-journals", scope: "full" }),
        TaskMan: Object.freeze({ id: "simple.workspace.taskman", scope: "full" }),
        HOT: Object.freeze({ id: "simple.workspace.hot", scope: "full" }),
        childDocs: Object.freeze({ id: "simple.workspace.child-docs", scope: "full" }),
        conditionDocs: Object.freeze({ id: "simple.workspace.condition-docs", scope: "full" }),
        "quick-notes": Object.freeze({ id: "simple.workspace.quick-notes", scope: "full" }),
        TaskManPlus: Object.freeze({ id: "simple.workspace.taskman-plus", scope: "full" }),
        sql: Object.freeze({ id: "simple.workspace.sql", scope: "chrome" }),
        constellation: Object.freeze({ id: "simple.workspace.constellation", scope: "chrome" }),
        reviewDocs: Object.freeze({ id: "simple.workspace.review-docs", scope: "chrome" }),
        fixedAssets: Object.freeze({ id: "simple.workspace.fixed-assets", scope: "chrome" }),
        weather: Object.freeze({ id: "simple.workspace.native.weather", scope: "native" }),
        stikynot: Object.freeze({ id: "simple.workspace.native.stikynot", scope: "native" }),
        statisticalCard: Object.freeze({ id: "simple.workspace.native.statistical-card", scope: "native" }),
        almanac: Object.freeze({ id: "simple.workspace.native.almanac", scope: "native" }),
        PicCaro: Object.freeze({ id: "simple.workspace.native.pic-caro", scope: "native" }),
    }),
    icons: Object.freeze({
        "documents.recent": "iconFile",
        "documents.favorite": "iconBookmark",
        "journal.recent": "iconCalendar",
        "task.list": "iconCheck",
        documents: "iconFile",
        tasks: "iconCheck",
        list: "iconList",
        stat: "iconGraph",
        chart: "iconGraph",
        calendar: "iconCalendar",
        note: "iconEdit",
        media: "iconRecord",
        utility: "iconTools",
        embed: "iconLink",
        complex: "iconWorkspace",
    }),
});
