import { WIDGET_PRESENTATION_CONTRACT_VERSION, type WidgetPresentationManifest } from "../../../widgetPresentation/types";

export const cardWidgetPresentation: WidgetPresentationManifest = Object.freeze({
    contractVersion: WIDGET_PRESENTATION_CONTRACT_VERSION,
    shell: Object.freeze({
        id: "card.elevated",
        variants: 3,
        exclude: Object.freeze({
            presentationIds: Object.freeze([
                "card.workspace.native.pic-caro",
            ]),
            contentVariants: Object.freeze(["timedate.dial"]),
        }),
        tokens: Object.freeze({
            background: "var(--hp-card-surface-raised)",
            border: "1px solid var(--hp-card-border)",
            borderRadius: "18px",
            boxShadow: "var(--hp-card-shadow-widget)",
        }),
    }),
    generic: Object.freeze({ id: "card.workspace.generic" }),
    kinds: Object.freeze({
        list: Object.freeze({ id: "card.workspace.list" }),
        task: Object.freeze({ id: "card.workspace.task" }),
        stat: Object.freeze({ id: "card.workspace.stat" }),
        chart: Object.freeze({ id: "card.workspace.chart" }),
        calendar: Object.freeze({ id: "card.workspace.calendar" }),
        note: Object.freeze({ id: "card.workspace.note" }),
        media: Object.freeze({ id: "card.workspace.media" }),
        utility: Object.freeze({ id: "card.workspace.utility" }),
        embed: Object.freeze({ id: "card.workspace.embed" }),
        complex: Object.freeze({ id: "card.workspace.complex" }),
        custom: Object.freeze({ id: "card.workspace.custom" }),
    }),
    widgets: Object.freeze({
        "latest-docs": Object.freeze({ id: "card.workspace.latest-docs", scope: "full" }),
        favorites: Object.freeze({ id: "card.workspace.favorites", scope: "full" }),
        "recent-journals": Object.freeze({ id: "card.workspace.recent-journals", scope: "full" }),
        TaskMan: Object.freeze({ id: "card.workspace.taskman", scope: "full" }),
        HOT: Object.freeze({ id: "card.workspace.hot", scope: "full" }),
        childDocs: Object.freeze({ id: "card.workspace.child-docs", scope: "full" }),
        conditionDocs: Object.freeze({ id: "card.workspace.condition-docs", scope: "full" }),
        "quick-notes": Object.freeze({ id: "card.workspace.quick-notes", scope: "full" }),
        TaskManPlus: Object.freeze({ id: "card.workspace.taskman-plus", scope: "full" }),
        sql: Object.freeze({ id: "card.workspace.sql", scope: "chrome" }),
        constellation: Object.freeze({ id: "card.workspace.constellation", scope: "chrome" }),
        reviewDocs: Object.freeze({ id: "card.workspace.review-docs", scope: "chrome" }),
        fixedAssets: Object.freeze({ id: "card.workspace.fixed-assets", scope: "chrome" }),
        enhancedDiary: Object.freeze({ id: "card.workspace.enhanced-diary", scope: "native" }),
        weather: Object.freeze({ id: "card.workspace.native.weather", scope: "native" }),
        stikynot: Object.freeze({ id: "card.workspace.native.stikynot", scope: "native" }),
        statisticalCard: Object.freeze({ id: "card.workspace.native.statistical-card", scope: "native" }),
        almanac: Object.freeze({ id: "card.workspace.native.almanac", scope: "native" }),
        PicCaro: Object.freeze({ id: "card.workspace.native.pic-caro", scope: "native" }),
        timedate: Object.freeze({ id: "card.workspace.native.timedate", scope: "native" }),
    }),
    icons: Object.freeze({
        "documents.recent": "iconFile",
        "documents.favorite": "iconBookmark",
        "journal.recent": "iconCalendar",
        "task.list": "iconCheck",
        documents: "iconFile",
        tasks: "iconCheck",
        list: "iconList",
        stat: "iconGraph",
        chart: "iconGraph",
        calendar: "iconCalendar",
        note: "iconEdit",
        media: "iconRecord",
        utility: "iconTools",
        embed: "iconLink",
        complex: "iconWorkspace",
    }),
});
