export const defaultClickEffects = [
    "(￣▽￣)~*",
    "(>_<)",
    "٩(◕‿◕｡)۶",
    "(；´д｀)ゞ",
    "☆*:.｡.o(≧▽≦)o.｡.:*☆",
    "ヾ(•ω•`)o",
    "ヽ(￣ω￣(。。 )ゝ",
    "(´• ω •`)",
    "(╯°□°）╯︵ ┻━┻",
    "¯_(ツ)_/¯",
    "(✧ω✧)",
    "(￢_￢)",
    "ಠ_ಠ",
    "(⁄ ⁄•⁄ω⁄•⁄ ⁄)",
    "ヾ(⌐■_■)ノ♪",
    "༼ つ ◕_◕ ༽つ",
    "(◕‿◕✿)",
    "｡：ﾟ(;´∩`;)ﾟ：｡",
    "ヽ(￣д￣;)ノ=3=3=3",
    "(๑•̀ㅂ•́)و✧",
    "╮(─▽─)╭",
    "(。>︿<)_θ",
    "٩(｡•́‿•̀｡)۶",
    "ヽ(￣▽￣)ﾉ",
    "(´･ω･`)",
    "(◐ω◑ )",
    "(◞‸◟ )",
    "Σ(っ°Д°;)っ",
    "⊙▃⊙",
    "(ノへ￣、)",
    "(づ￣ ³￣)づ",
    "٩(˘◡˘)۶",
    "Ｏ(≧口≦)Ｏ",
    "★~(◠﹏⊙✿)",
    "✪ ω ✪",
    "●﹏●",
    "（>ω<）",
    "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡",
    "(*/ω＼*)",
    "(,,•́ . •̀,,)",
];

export const cursorIconMap: { [key: string]: string } = {
    CYWL1: "/plugins/siyuan-homepage/asset/mouseIcon/CYWL1.png",
    CYWL2: "/plugins/siyuan-homepage/asset/mouseIcon/CYWL2.ico",
    WDSJsword: "/plugins/siyuan-homepage/asset/mouseIcon/WDSJsword.cur",
    WDSJpickaxe: "/plugins/siyuan-homepage/asset/mouseIcon/WDSJpickaxe.cur",
    cat1: "/plugins/siyuan-homepage/asset/mouseIcon/cat1.ico",
    cat2: "/plugins/siyuan-homepage/asset/mouseIcon/cat2.ico",
    cat3: "/plugins/siyuan-homepage/asset/mouseIcon/cat3.ico",
    arrow1: "/plugins/siyuan-homepage/asset/mouseIcon/arrow1.ico",
    arrow2: "/plugins/siyuan-homepage/asset/mouseIcon/arrow2.ico",
    arrow3: "/plugins/siyuan-homepage/asset/mouseIcon/arrow3.ico",
    arrow4: "/plugins/siyuan-homepage/asset/mouseIcon/arrow4.ico",
    arrow5: "/plugins/siyuan-homepage/asset/mouseIcon/arrow5.ico",
    arrow6: "/plugins/siyuan-homepage/asset/mouseIcon/arrow6.ico",
    arrow7: "/plugins/siyuan-homepage/asset/mouseIcon/arrow7.ico",
    LOL1: "/plugins/siyuan-homepage/asset/mouseIcon/LOL1.ico",
    LOL2: "/plugins/siyuan-homepage/asset/mouseIcon/LOL2.ico",
    LOL3: "/plugins/siyuan-homepage/asset/mouseIcon/LOL3.ico",
    LOL4: "/plugins/siyuan-homepage/asset/mouseIcon/LOL4.ico",
    CBPK2077: "/plugins/siyuan-homepage/asset/mouseIcon/CBPK2077.ico",
};

export const fallingIconList = [
    "snow",
    "cherry",
    "cherryPetal",
    "greenery",
    "mapleLeaf",
    "bodhiLeaf",
    "ginkgoLeaf",
    "dandelion",
    "bambooLeaf",
    "QZHIHE",
    "paperPlane",
    "HMBB",
    "PDX",
    "Rinka",
    "heart",
    "rose",
    "star",
];